Update action.yaml

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -73,4 +73,5 @@ runs:
       shell: bash
       run: |
         docker run --rm --mount type=bind,source=${{ inputs.directory}},target=/scandir -e CLAMAV_NO_CLAMD=true clamav/clamav:stable clamscan ${{ env.SCANNERS_ARGS }} /scandir
-        exit $? 
+        echo "SCAN_RESULT=$?" >> $GITHUB_ENV # 0 : No virus found, 1 : Virus(es) found, 2 : Some error(s) occured. 
+        exit ${{ env.SCAN_RESULT }} 
